version: "3.9"

services:
  redis:
    image: redis:7
    container_name: skillportal-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]

  db:
    image: mysql:8.0
    container_name: skillportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: skill_portal
      MYSQL_USER: skill_user
      MYSQL_PASSWORD: skill_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/skill-portal-schema.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    container_name: skillportal-backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: mysql://skill_user:skill_pass@db:3306/skill_portal
      REDIS_URL: redis://redis:6379
      JWT_SECRET: please-skills
      JWT_EXPIRES_IN: 1d
      BCRYPT_SALT_ROUNDS: 10
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skillportal-frontend
    environment:
      API_BASE: http://localhost:4000/api
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
